import React from 'react';
import { BellRing } from 'lucide-react';
import { useCycleNotifications } from './useCycleNotifications';

export function NotificationPreferences({ enabled }: { enabled: boolean }) {
  const { preferences, status, loading, save, enablePush } = useCycleNotifications(enabled);
  if (!enabled) return null;
  return <section className="rounded-[1.5rem] border border-white/10 bg-[#14231e] p-4"><div className="flex items-start gap-3"><BellRing className="mt-0.5 h-5 w-5 text-teal-300" /><div className="min-w-0 flex-1"><h3 className="font-bold text-white">یادآورهای اختیاری</h3><p className="mt-1 text-xs leading-5 text-zinc-400">اعلان‌ها خنثی هستند و جزئیات چرخه را روی صفحه قفل نشان نمی‌دهند.</p></div></div><div className="mt-4 space-y-3"><label className="flex min-h-11 items-center justify-between gap-3 text-sm text-zinc-200"><span>یادآور ثبت روزانه</span><input type="checkbox" checked={preferences.dailyLogEnabled} onChange={(event) => void save({ dailyLogEnabled: event.target.checked })} /></label><label className="flex min-h-11 items-center justify-between gap-3 text-sm text-zinc-200"><span>هشدار نزدیک تخمک‌گذاری</span><input type="checkbox" checked={preferences.ovulationEnabled} onChange={(event) => void save({ ovulationEnabled: event.target.checked })} /></label><label className="flex items-center justify-between gap-3 text-sm text-zinc-200"><span>زمان روزانه</span><input aria-label="زمان یادآور روزانه" type="time" value={preferences.dailyLogTime} onChange={(event) => void save({ dailyLogTime: event.target.value })} className="rounded-lg border border-white/10 bg-black/20 px-2 py-1 text-xs text-white" /></label><button type="button" disabled={loading} onClick={() => void enablePush()} className="min-h-11 w-full rounded-xl bg-teal-400 px-4 text-sm font-bold text-[#09221b] disabled:opacity-50">فعال‌سازی اعلان این دستگاه</button>{status ? <p role="status" className="text-xs leading-5 text-zinc-400">{status}</p> : null}</div></section>;
}
